### ISSUE TITLE
I just tried to install via pip but it fails

### ISSUE THREAD

**Issue by alex-leonhardt** [rafaduran/python-mcollective#23]
Hi,

OS: Fedora20
Python: 2.7

I just tried to install this via pip, but it seems to fail with : 

Downloading/unpacking python-mcollective
  Could not find a version that satisfies the requirement python-mcollective (from versions: 0.0.1.dev3)
Cleaning up...
No distributions matching the version for python-mcollective
Storing complete log in ~/.pip/pip.log

and the log : 

```
------------------------------------------------------------
/bin/pip run on Wed Oct  1 14:35:06 2014
Downloading/unpacking python-mcollective

  Getting page https://pypi.python.org/simple/python-mcollective/
  URLs to search for versions for python-mcollective:
  * https://pypi.python.org/simple/python-mcollective/
  Analyzing links from page https://pypi.python.org/simple/python-mcollective/
    Found link https://pypi.python.org/packages/source/p/python-mcollective/python-mcollective-0.0.1.dev3.tar.gz#md5=a952f8dcf03aed9c9ad953c1cc48efcd (from https://pypi.python.org/simple/python-mcollective/), version: 0.0.1.dev3
  Ignoring link https://pypi.python.org/packages/source/p/python-mcollective/python-mcollective-0.0.1.dev3.tar.gz#md5=a952f8dcf03aed9c9ad953c1cc48efcd (from https://pypi.python.org/simple/python-mcollective/), version 0.0.1.dev3 is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement python-mcollective (from versions: 0.0.1.dev3)

Cleaning up...

  Removing temporary dir /tmp/pip_build_root...
No distributions matching the version for python-mcollective

Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/site-packages/pip/req.py", line 1085, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/site-packages/pip/index.py", line 309, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for python-mcollective
```

**Comment by rafaduran** [comment]
@alex-leonhardt I'm sorry for the very late answer, but there is not production releases yet, so you need --pre option:

```
pip install --pre python-mcollctive
```

I will review docs, since they are wrong.

**Comment by rafaduran** [comment]
Documentation was already fixed, so closing this.
